version: '3'

services:
  web:
    build: .
    container_name: console-container
    image: streamdal/console:latest
    environment:
      - STREAMDAL_GRPC_WEB_URL=http://host.docker.internal:9091
      - STREAMDAL_GRPC_AUTH_TOKEN="1234"
    ports:
      - "3000:3000"
